version: '2'
services:
  nginx:
    build: ./nginx
    command: nginx -g 'daemon off;'
    image: mortonprod/nginx
    mem_limit: 2g
    cpu_shares: 256
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "27017:433"
    depends_on:
      - app
  db: 
    build: "./db" #Use docker file in this directory to create mongdb image. 
    image: "mortonprod/mongodb"
    volumes:
      - /data/db #links host ./db/store to default mongodb location.
    #ports:
    #- 27017 #Any container can link to this.
  app:
    build: .
    command: npm run prod:start
    image: "mortonprod/app"
    volumes:
      - ./dist:/usr/src/app/dist #Attach our file into our node enviroment.
      - ./node_modules:/usr/src/app/node_modules 
      - ./ssl:/usr/src/app/ssl
    ports:
      - "433:433"
    #links: #Links db service(like web) to database name.It then is accessed via url. 
    # - "db:db" #outside:inside
    depends_on:
      - db #Specify to create db instance before we create node
